name: Sync with Apache Geode Native Develop

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync-develop:
    runs-on: ubuntu-latest
    name: Sync develop with upstream latest
    steps:
    # Step 1: run a standard checkout action, provided by github
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: develop
        # submodules: 'recursive'     ### possibly needed in your situation

    # Step 2: run this sync action - specify the upstream repo, upstream branch to sync with, and target sync branch
    - name: Pull (Fast-Forward) upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v2.3
      with:
        upstream_repository: apache/geode-native
        upstream_branch: develop
        target_branch: develop
        git_pull_args: --ff-only                    # optional arg use, defaults to simple 'pull'
       # github_token: ${{ secrets.GITHUB_TOKEN }}   # optional, for accessing repos that require authentication

#  sync-test-actions:
#    runs-on: ubuntu-latest
#    name: Sync test-actions with develop
#    steps:
#    # Step 1: run a standard checkout action, provided by github
#    - name: Checkout
#      uses: actions/checkout@v2
#      with:
#        ref: test-actions
#        # submodules: 'recursive'     ### possibly needed in your situation
#
#    # Step 2: run this sync action - specify the upstream repo, upstream branch to sync with, and target sync branch
#    - name: Pull (Fast-Forward) upstream changes
#      id: sync
#      uses: aormsby/Fork-Sync-With-Upstream-action@v2.3
#      with:
#        upstream_repository: apache/geode-native
#        upstream_branch: develop
#        target_branch: test-actions
#        git_pull_args: --rebase                    # optional arg use, defaults to simple 'pull'
#        git_push_args: --force-with-lease
#       # github_token: ${{ secrets.GITHUB_TOKEN }}   # optional, for accessing repos that require authentication
#
#  sync-no-non-virtual-dtor:
#    runs-on: ubuntu-latest
#    name: Sync no-non-virtual-dtor with develop
#    steps:
#    # Step 1: run a standard checkout action, provided by github
#    - name: Checkout
#      uses: actions/checkout@v2
#      with:
#        ref: no-non-virtual-dtor
#        # submodules: 'recursive'     ### possibly needed in your situation
#
#    # Step 2: run this sync action - specify the upstream repo, upstream branch to sync with, and target sync branch
#    - name: Pull (Fast-Forward) upstream changes
#      id: sync
#      uses: aormsby/Fork-Sync-With-Upstream-action@v2.3
#      with:
#        upstream_repository: apache/geode-native
#        upstream_branch: develop
#        target_branch: no-non-virtual-dtor
#        git_pull_args: --rebase                    # optional arg use, defaults to simple 'pull'
#        git_push_args: --force-with-lease
#       # github_token: ${{ secrets.GITHUB_TOKEN }}   # optional, for accessing repos that require authentication
