name: Things That Do Not Work CI

on:
  push:
  pull_request:

env:
  GEODE_VERSION: 1.13.1

jobs:
  acceptance-test-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2016, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: cache geode
      uses: actions/cache@v2.1.4
      id: cache-geode-windows
      with:
        path: C:\apache-geode
        key: apache-geode-windows
    - name: install geode
      env:
        CACHE_HIT: ${{steps.cache-geode-windows.outputs.cache-hit}}
      run: |
        If ($env:CACHE_HIT -ne "true") {
          iwr "https://downloads.apache.org/geode/$env:GEODE_VERSION/apache-geode-$env:GEODE_VERSION.tgz" -OutFile apache-geode.tgz
          7z x apache-geode.tgz
          7z x apache-geode.tar
          mv apache-geode-$env:GEODE_VERSION C:\apache-geode
          rm apache*.t*
        }
    - name: install doxygen
      run: choco install doxygen.install -confirm
    - name: install nunit
      run: choco install nunit.install --version 2.6.4 -confirm
    - name: install openssl
      run: choco install openssl -confirm
    - name: check docker system info
      run: |
        docker system info
    - name: mkdir build
      run: mkdir C:\build
    - name: cmake configure
      run: |
        mkdir C:\geode-native
        mv * C:\geode-native\
        cd C:\geode-native
        $env:GEODE_HOME="C:\apache-geode"
        cmake -BC:\build -A x64 -T "v141,version=14.16,host=x64" -DCMAKE_SYSTEM_VERSION="10.0.16299.0"
    - name: cmake build
      run: cmake --build C:\build --target cpp-acceptance-test -- /m
    - name: acceptance tests
      run: cmake -E chdir C:\build\cppcache\acceptance-test ctest -j1 --output-on-failure --schedule-random
